// Generated by CoffeeScript 1.7.1
(function() {
  var $background, $foreground, $window, BACKGROUND_DEPTH, FOREGROUND_DEPTH, fetchPhoto, parallaxMouseMove, windowHeight, windowResize, windowWidth;

  $(document).ready(function() {
    _500px.init({
      sdk_key: 'f5b30e8f2f455a41830df6010f4128c41b45c700'
    });
    $('.photo_url').bind('keyup', function() {
      if ($('.photo_url').val().length) {
        return $('.go').removeClass('hidden').addClass('animate_in');
      } else {
        return $('.go').addClass('hidden').removeClass('animate_in');
      }
    });
    $('.photo_url').on('paste', function() {
      return setTimeout((function() {
        var clean_str, str;
        str = $('.photo_url').val();
        clean_str = str.match(/^https:\/\/prime.500px.com\/photos\/\d+/)[0];
        return $('.photo_url').val(clean_str);
      }), 10);
    });
    $('.example').on('click', function() {
      $('.photo_url').val('https://prime.500px.com/photos/37790924').focus();
      return $('.go').removeClass('hidden').addClass('animate_in');
    });
    $('#url').on('submit', function(event) {
      var str;
      event.preventDefault();
      str = $('.photo_url').val();
      if (str.match(/^https:\/\/prime.500px.com\/photos\/\d+/)) {
        return fetchPhoto(str.match(/\/photos\/(\d+)/)[1]);
      } else {
        return $('.step_1').addClass('invalid_url');
      }
    });
    $('.links a').on('click', function(event) {
      var className;
      event.preventDefault();
      className = $(this).attr('href').replace('#', '');
      return $('.step_2').removeClass('fb ig li tw').addClass(className);
    });
    $('.back').on('click', function() {
      $('.step_2').addClass('animate_out');
      $('.overlay').removeClass('light');
      $('header').removeClass('dark');
      setTimeout((function() {
        $('.photo_url').val('');
        $('.go').addClass('hidden');
        $('.step_2').addClass('hidden');
        return $('.step_1').removeClass('hidden').addClass('animate_in');
      }), 400);
      return setTimeout((function() {
        $('.step_2').removeClass('animate_out animate_in');
        $('.step_1').removeClass('invalid_url');
        return $('body').off('mousemove', parallaxMouseMove);
      }), 400);
    });
    if (window.location.hash.match(/#\d+/)) {
      return fetchPhoto(window.location.hash.replace('#', ''));
    }
  });

  $background = $('.background');

  $foreground = $('.step_2');

  BACKGROUND_DEPTH = 20;

  FOREGROUND_DEPTH = 10;

  $window = $(window);

  windowWidth = windowHeight = 0;

  windowResize = function() {
    windowWidth = $window.width();
    return windowHeight = $window.height();
  };

  $(function() {
    return windowResize();
  });

  $window.on('resize', windowResize);

  parallaxMouseMove = function(e) {
    var x, y;
    x = e.pageX;
    y = e.pageY;
    x = -((x / windowWidth) - 0.5);
    y = -((y / windowHeight) - 0.5);
    $background.css({
      transform: "translateX(" + (Math.round(x * BACKGROUND_DEPTH)) + "px) translateY(" + (Math.round(y * BACKGROUND_DEPTH)) + "px)"
    });
    return $foreground.css({
      transform: "translateX(" + (x * FOREGROUND_DEPTH) + "px) translateY(" + ((y * FOREGROUND_DEPTH) + 10) + "px)"
    });
  };

  fetchPhoto = function(photoId) {
    _500px.api("/photos/" + photoId, function(response) {
      $('body').removeClass('loading');
      if (response.success) {
        $('.prime-photo').css('background-image', "url(" + response.data.photo.image_url + ")");
        return $('.prime-photo').addClass('fb');
      } else {
        return alert('Error');
      }
    });
    $('.step_1').addClass('animate_out').removeClass('animate_in');
    $('.buy .button').attr('href', "https://prime.500px.com/photos/" + photoId);
    setTimeout((function() {
      $('.step_1').addClass('hidden');
      return setTimeout((function() {
        $('.step_2').removeClass('hidden').addClass('animate_in');
        $('.overlay').addClass('light');
        $('header').addClass('dark');
        return $('body').on('mousemove', parallaxMouseMove);
      }), 400);
    }), 400);
    setTimeout((function() {
      return $('.step_1, .step_2').removeClass('animate_out animate_in');
    }), 2000);
    $('body').addClass('loading');
    return window.location.hash = "" + photoId;
  };

}).call(this);
